spring:
  datasource:
    url: jdbc:h2:mem:database
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-drop
    defer-datasource-initialization: true

payments:
  secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
  password: ":"
payment-timeout: 60
