spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:database
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none

payments:
  secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
  password: ":"
payment-timeout: 60
